POST http://localhost:3001/api/polls
Content-Type: application/json

{
    "question": "test?",
    "options": {"1": {"option": "first option", "votes": 1}, "2": {"option": "second option", "votes": 3}}
}